// 独立ウィンドウ用の要約ロジック
const OLLAMA_URL = "http://localhost:11434/api/generate";
const DEFAULT_MODEL = "gemma3:12b";

document.addEventListener('DOMContentLoaded', async () => {
    // 「閉じる」ボタンの制御
    document.getElementById('close-btn').addEventListener('click', () => {
        window.close();
    });

    const subjectElem = document.getElementById('subject');
    const statusElem = document.getElementById('status');
    const summaryElem = document.getElementById('summary');

    // URLパラメータから messageId を取得
    const urlParams = new URLSearchParams(window.location.search);
    const messageId = urlParams.get('messageId');

    if (!messageId) {
        statusElem.textContent = "エラー: メールの情報が渡されませんでした。";
        return;
    }

    try {
        statusElem.textContent = "メール内容を取得中...";
        // バックグラウンドに本文取得を依頼
        const emailInfo = await browser.runtime.sendMessage({
            command: "getEmailContentForSummary",
            messageId: parseInt(messageId)
        });

        if (emailInfo.error) {
            throw new Error(emailInfo.error);
        }

        subjectElem.textContent = "件名: " + emailInfo.subject;
        statusElem.textContent = "Ollama (" + DEFAULT_MODEL + ") で要約を生成中...";
        summaryElem.textContent = "考え中...";

        // 現在の日時を取得
        const today = new Date().toLocaleString('ja-JP');

        // Ollama へのリクエスト
        const prompt = `あなたはメール管理のアシスタントです。
以下の情報を元に、メールスレッドの内容を詳しく、かつ分かりやすく日本語で要約してください。

【コンテキスト情報】
分析実行日時 (現在): ${today}
メールの受信日時: ${emailInfo.date}

【要約の指示】
・単なる短縮ではなく、重要な論点や決定事項、期限、返信が必要な事項などを漏れなく含めてください。
・これまでのやり取りの経緯（誰が何を要望したか）と、今回のメールでの最新状況を区別して記述してください。
・Markdown形式（箇条書きや太字）を効果的に使って、視認性高く出力してください。
・3行にこだわらず、必要な情報を網羅できる適切な長さ（10行程度まで）で作成してください。

---
${emailInfo.body}
---
要約：`;

        const response = await fetch(OLLAMA_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                model: DEFAULT_MODEL,
                prompt: prompt,
                stream: false
            })
        });

        if (!response.ok) {
            if (response.status === 404) {
                throw new Error(`モデル '${DEFAULT_MODEL}' が見つかりませんでした。'ollama pull ${DEFAULT_MODEL}' を実行してください。`);
            }
            throw new Error(`Ollama エラー: ${response.statusText}`);
        }

        const data = await response.json();
        const summaryText = data.response.trim();

        // Markdown を解析して表示
        summaryElem.innerHTML = marked.parse(summaryText);
        statusElem.textContent = "完了";

        // Obsidian ボタンを表示してイベント登録
        const obsidianBtn = document.getElementById('obsidian-btn');
        obsidianBtn.style.display = 'inline-block';
        obsidianBtn.onclick = () => {
            // YYYYMMDD 形式の日付を作成
            const now = new Date();
            const yyyymmdd = now.getFullYear() +
                String(now.getMonth() + 1).padStart(2, '0') +
                String(now.getDate()).padStart(2, '0');

            const fileName = `Thunderbird/メール要約_${emailInfo.subject.replace(/[:/\\?%*|"<>]/g, '_')}_${yyyymmdd}`;
            const fileContent = `---
date: ${today}
original_date: ${emailInfo.date}
source: Thunderbird Summary
tags: Thunderbird
---
# ${emailInfo.subject}

#Thunderbird

## AI 要約
${summaryText}

---
*Generated by Thunderbird Add-on (Ollama Gemma 3)*`;

            const obsidianUri = `obsidian://new?file=${encodeURIComponent(fileName)}&content=${encodeURIComponent(fileContent)}`;
            window.location.href = obsidianUri;
        };

    } catch (e) {
        console.error("[Summary Window Error]", e);
        statusElem.textContent = "エラーが発生しました";
        if (e.message.includes("Failed to fetch")) {
            summaryElem.textContent = "Ollama に接続できません。Ollama が起動しているか、OLLAMA_ORIGINS の設定を確認してください。";
        } else {
            summaryElem.textContent = e.message;
        }
    }
});
