// 独立ウィンドウ用の要約ロジック
const OLLAMA_URL = "http://localhost:11434/api/generate";
const DEFAULT_MODEL = "gemma3:12b"; // Windows版はモデル固定

let currentEmailInfo = null;
let currentLength = "medium"; // デフォルトの長さ
let currentSummaryMarkdown = ""; // Obsidian出力用にマークダウンを保持

document.addEventListener('DOMContentLoaded', async () => {
    // UI要素の取得
    const subjectElem = document.getElementById('subject');
    const statusElem = document.getElementById('status');
    const summaryElem = document.getElementById('summary');
    const controlsElem = document.getElementById('length-controls'); // HTML側に必要
    const obsidianBtn = document.getElementById('obsidian-btn');

    // 「閉じる」ボタンの制御
    document.getElementById('close-btn').addEventListener('click', () => {
        window.close();
    });

    // 長さ切り替えボタンのイベント登録
    document.querySelectorAll('.length-btn').forEach(btn => {
        btn.addEventListener('click', async () => {
            const newLength = btn.getAttribute('data-length');
            if (newLength === currentLength) return;

            // ボタンの見た目を更新
            document.querySelectorAll('.length-btn').forEach(b => b.classList.remove('active'));
            btn.classList.add('active');

            currentLength = newLength;
            await generateSummary();
        });
    });

    // URLパラメータから messageId を取得
    const urlParams = new URLSearchParams(window.location.search);
    const messageId = urlParams.get('messageId');

    if (!messageId) {
        statusElem.textContent = "エラー: メールの情報が渡されませんでした。";
        return;
    }

    try {
        statusElem.textContent = "メール内容を取得中...";
        // バックグラウンドに本文取得を依頼
        currentEmailInfo = await browser.runtime.sendMessage({
            command: "getEmailContentForSummary",
            messageId: parseInt(messageId)
        });

        if (currentEmailInfo.error) {
            throw new Error(currentEmailInfo.error);
        }

        subjectElem.textContent = "件名: " + currentEmailInfo.subject;

        // 要約実行
        if (controlsElem) controlsElem.style.display = 'flex';
        await generateSummary();

        // Obsidian ボタンを表示してイベント登録
        obsidianBtn.style.display = 'inline-block';
        obsidianBtn.onclick = () => {
            if (!currentEmailInfo) return; // currentEmailInfo が取得できているか確認

            // YYYYMMDD 形式の日付をファイル名用に作成
            const now = new Date();
            const yyyymmdd = now.getFullYear() +
                String(now.getMonth() + 1).padStart(2, '0') +
                String(now.getDate()).padStart(2, '0');

            // ファイル名の生成
            const fileName = `Thunderbird/メール要約_${currentEmailInfo.subject.replace(/[:/\\?%*|"<>]/g, '_')}_${yyyymmdd}`;

            // ファイル内容の生成
            const fileContent = `---
date: ${new Date().toLocaleString('ja-JP')}
original_date: ${currentEmailInfo.date}
source: Thunderbird Summary
tags: Thunderbird
---
# ${currentEmailInfo.subject}

## AI 要約 (${currentLength === 'short' ? '短め' : currentLength === 'long' ? '長め' : '標準'})
${currentSummaryMarkdown}

---
Generated by Thunderbird Add-on (Ollama ${DEFAULT_MODEL})`;

            // URI スキームの構築と遷移
            const obsidianUri = `obsidian://new?file=${encodeURIComponent(fileName)}&content=${encodeURIComponent(fileContent)}`;
            window.location.href = obsidianUri;
        };

    } catch (e) {
        console.error("[Summary Window Error]", e);
        statusElem.textContent = "エラーが発生しました";
        summaryElem.textContent = e.message;
    }
});

async function generateSummary() {
    const statusElem = document.getElementById('status');
    const summaryElem = document.getElementById('summary');

    statusElem.textContent = `Ollama (${DEFAULT_MODEL}) で要約を生成中...`;
    summaryElem.textContent = "考え中...";

    // 現在の日時を取得
    const today = new Date().toLocaleString('ja-JP', {
        year: 'numeric', month: '2-digit', day: '2-digit',
        weekday: 'short', hour: '2-digit', minute: '2-digit'
    });

    // 長さに応じた指示（Mac版のロジックを移植）
    let lengthInstruction = "";
    if (currentLength === "short") {
        lengthInstruction = "非常に簡潔に、全体で5行程度でまとめてください。詳細よりも結論を優先してください。ハルシネーションを避けるため確実な情報のみ記述してください。";
    } else if (currentLength === "long") {
        lengthInstruction = "具体的な背景、ニュアンス、各発言の詳細を詳しく記述してください。情報の網羅性を重視します。";
    } else {
        lengthInstruction = "標準的な長さ（10行程度）で、重要な結論と経緯のバランス良くまとめてください。";
    }

    const prompt = `あなたは高度なメール解析アシスタントです。
以下の情報を元に、メールスレッドの内容を詳しく、かつ分かりやすく日本語で要約してください。
【要約のボリューム制限】: ${lengthInstruction}

【コンテキスト情報】
分析実行日時 (現在): ${today}
メールの受信日時: ${currentEmailInfo.date}

【要約の指示】
1. **日付の形式 (厳守)**: 本文中で日付に言及する場合は、必ず **「MM/DD (曜日)」** （例: 02/18 (水)）の形式を使用してください。
   - **重要**: 曜日は計算せず、入力テキスト（引用ヘッダー）にある曜日をそのまま書き写してください。
2. **項目の強調 (厳守)**: 項目名と内容をコロンで区切る場合、項目名（コロンの前）を必ず太字（**で囲む）にしてください。
   - 例: **最新状況**: ..., **決定事項**: ..., **今後のアクション**: ...
3. **最新状況の要約**: 今回のメールの結論、依頼事項、背景を整理して最初に記述してください。
4. **時系列での経緯整理**: これまでの経緯を**「古い順（過去から現在へ）」**で箇条書き（マークダウンのリスト形式 - ）に従って記述してください。
   - 形式例: - **MM/DD (曜日)** (発言者): 内容の要約
5. **今後のアクション**: 必要に応じて記載。決定事項、期限、返信が必要な事項などを漏れなく含めてください。ハルシネーションを避けるため確実な情報のみ記述してください。
6. **引用文の保持**: 引用文は引用元を明示してください。
---
${currentEmailInfo.body}
---
要約：`;

    try {
        const response = await fetch(OLLAMA_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                model: DEFAULT_MODEL,
                prompt: prompt,
                stream: false
            })
        });

        if (!response.ok) {
            throw new Error(`Ollama エラー: ${response.statusText}`);
        }

        const data = await response.json();
        currentSummaryMarkdown = data.response.trim();

        // Markdown を解析して表示
        summaryElem.innerHTML = marked.parse(currentSummaryMarkdown);
        statusElem.textContent = "完了 (" + (currentLength === 'short' ? '短め' : currentLength === 'long' ? '長め' : '標準') + ")";

    } catch (err) {
        console.error(err);
        summaryElem.textContent = "再生成エラー: " + err.message;
        statusElem.textContent = "エラー";
    }
}